# Generated by Django 4.0.6 on 2023-02-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='decription',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('subscriber', 'subscriber'), ('regular', 'regular'), ('moderator', 'moderator')], default='regular', max_length=50),
        ),
    ]
