# Generated by Django 4.0.6 on 2023-01-31 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='articleSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True, verbose_name='Series slug')),
                ('publised', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Series',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, default='no subtittle', max_length=200, null=True)),
                ('article_slug', models.SlugField(unique=True, verbose_name='Article slug')),
                ('content', models.TextField()),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='publised date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified date')),
                ('series', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='core.articleseries')),
            ],
        ),
    ]
