# Generated by Django 4.0.6 on 2023-02-05 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.RenameField(
            model_name='articleseries',
            old_name='publised',
            new_name='published',
        ),
    ]
