# Generated by Django 4.0.6 on 2023-02-06 11:17

from django.db import migrations, models
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='note',
            field=tinymce.models.HTMLField(blank=True, default='no note yet', null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(blank=True, default='no content yet', null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='modified date'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='publised date'),
        ),
        migrations.AlterField(
            model_name='articleseries',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date published'),
        ),
    ]
