# Generated by Django 4.0.6 on 2023-02-13 10:39

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_article_author_alter_articleseries_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleseries',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=core.models.articleSeries.image_upload_to),
        ),
    ]
