# Generated by Django 4.0.6 on 2023-02-14 12:01

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleseries',
            name='image',
            field=models.ImageField(max_length=200, upload_to=core.models.articleSeries.image_upload_to),
        ),
    ]
