# Generated by Django 4.0.6 on 2023-02-14 12:26

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_articleseries_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='images/favicon.PNG', upload_to=core.models.Article.image_upload_to),
        ),
        migrations.AlterField(
            model_name='articleseries',
            name='image',
            field=models.ImageField(upload_to=core.models.articleSeries.image_upload_to),
        ),
    ]
